_id: "402703512393220096"
name: 199-error
model: ""
createdAt: 2024-01-17T05:59:59.225Z
updatedAt: 2024-01-17T05:59:59.225Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/ad4c3fef05e2841da5b17fb6a4e2e34b.png
gitType: simple
temperature: 1
topP: 1
