_id: "402703512393220096"
name: 199-error
description: null
model: gpt-3.5-turbo
createdAt: 2024-01-17T05:59:59.225Z
updatedAt: 2024-01-17T06:00:22.131Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/ad4c3fef05e2841da5b17fb6a4e2e34b.png
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
